import type { AnalysisResult } from "./types";

// Visual development fixture. Lets the table + summary be built before the
// API is wired in. Numbers and reasoning chosen to exercise every confidence
// band.
export const sampleResult: AnalysisResult = {
  imageQualityNotes: "Mixed angles, slight glare on top shelf",
  narrative: "",
  imageWidth: 1600,
  imageHeight: 1067,
  bottles: [
    { id: "bottle_1", bbox: { x: 0.06, y: 0.18, w: 0.07, h: 0.62 } },
    { id: "bottle_2", bbox: { x: 0.15, y: 0.17, w: 0.07, h: 0.63 } },
    { id: "bottle_3", bbox: { x: 0.24, y: 0.18, w: 0.07, h: 0.62 } },
    { id: "bottle_4", bbox: { x: 0.34, y: 0.16, w: 0.07, h: 0.64 } },
    { id: "bottle_5", bbox: { x: 0.44, y: 0.18, w: 0.07, h: 0.62 } },
    { id: "bottle_6", bbox: { x: 0.54, y: 0.18, w: 0.07, h: 0.62 } },
    { id: "bottle_7", bbox: { x: 0.64, y: 0.19, w: 0.07, h: 0.61 } },
    { id: "bottle_8", bbox: { x: 0.74, y: 0.19, w: 0.07, h: 0.61 } },
    { id: "bottle_9", bbox: { x: 0.84, y: 0.2, w: 0.07, h: 0.6 } },
  ],
  wines: [
    {
      bottleIds: ["bottle_1", "bottle_2"],
      producer: "Domaine Vacheron",
      wine: "Sancerre",
      vintage: 2022,
      region: "Loire",
      sizeMl: 750,
      count: 2,
      confidence: 92,
      reasoning: "Label clear",
      estimatedPriceGbp: 28,
    },
    {
      bottleIds: ["bottle_3"],
      producer: "Joseph Drouhin",
      wine: "Chablis",
      vintage: 2021,
      region: "Burgundy",
      sizeMl: 750,
      count: 1,
      confidence: 88,
      reasoning: "Label clear",
      estimatedPriceGbp: 24,
    },
    {
      bottleIds: ["bottle_4", "bottle_5"],
      producer: "Guigal",
      wine: "Côtes du Rhône",
      vintage: 2020,
      region: "Rhône",
      sizeMl: 750,
      count: 2,
      confidence: 86,
      reasoning: "Label clear",
      estimatedPriceGbp: 14,
    },
    {
      bottleIds: ["bottle_6"],
      producer: "Antinori",
      wine: "Tignanello",
      vintage: 2019,
      region: "Tuscany",
      sizeMl: 750,
      count: 1,
      confidence: 78,
      reasoning: "Angled",
      estimatedPriceGbp: 110,
    },
    {
      bottleIds: ["bottle_7"],
      producer: "Pol Roger",
      wine: "Brut Réserve",
      vintage: null,
      region: "Champagne",
      sizeMl: 750,
      count: 1,
      confidence: 72,
      reasoning: "Glare",
      estimatedPriceGbp: 48,
    },
    {
      bottleIds: ["bottle_8"],
      producer: "Château Lanessan",
      wine: "Haut-Médoc",
      vintage: null,
      region: "Bordeaux",
      sizeMl: 750,
      count: 1,
      confidence: 64,
      reasoning: "Partial vintage",
      estimatedPriceGbp: 22,
    },
    {
      bottleIds: ["bottle_9"],
      producer: null,
      wine: null,
      vintage: null,
      region: null,
      sizeMl: 750,
      count: 1,
      confidence: 41,
      reasoning: "Label obscured",
      estimatedPriceGbp: 25,
    },
  ],
};
